---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgAuN7Sie8MumPtJLHw62VJ8hnTWxY61goD8vxj5Ig8nrcxyfMv03YyLL951uYkOU6/P96iysqqbtODHibkDpMYo1/Od4+39IIK6EFaq7IDNH2SQNpS42/vG06VtSo+yJ9bm22Ew787hi4OoQPuREB2FUcRRwKLs/EyUS0Y8R7QA3yMppTuR6TUjKLrBEPCEcN/joqtU3WVZxpLWP13jYgLhw66jZirO7/PWWL3E5kn3IWw5x2gYe6BJs0I+3m5NA6uKJtzcpbqeeZxCwKNOXl9KWYfZ1gTu3GunBv0rAbhWb7JtumQefDbdsdgMhy0Qi7JYk2YMJfjfJfW3gIoXnVZRhVZTw0fqNuG6qVxaKX3tmVIUc97lcV0gjv5mxihPgU4wlI4ojVjPJofU4wdYUm/s2jexwcQe8chnI9FD1IoWrKxno8GzzsIQ5M2tr5y5kdhPZJ1cBav9u+SnrY1Dyr/3xR0dsnh4GltcyXaykh2pplC3adCZYikAEtCsVXhn6c2YfSfNI4M8rHA6R1pEHM1DGb6ZoJTWYiTli/nJeZnSgAw22ruZiXfmCu1pNl5R5lwmuDTKHoTFSceVPvVsPg5mWQhhSPWNuS7ApoLUMT9wTIRzh6BQVHD6NFtxaTi4SNUgLUtZOp7rntre0sxWZ+mhtmxY2p1DwXlA3vHOrm07zhptfIdDKFzn/XANWEv2Q9xEkd97W64RHruWWEEX5JmXb/d3cZjOAEYBHG7edRGZqr/OJBNku8G/
    email: AgDH628Kg9iapkxNwvDLUR8usEF5peKIpIHuU9oZkfowXunlaEmZAFZ19KrFyZIb4RDua3PQXwfGjfGg3mIsL4re5SaY54FmCgznL3EzDqRMIC/9fn/nqp/cxWXjCJ9NkyBlzllkJbjVRGYt/PoKE2zlUh3bisB/b8qnNhzBOmg6aQ2gOU3vaXkfv4TF+vmGpygGM46E1eiV+HqQUnYUtQomuDwOETyvOphGu9iiDqulWXgCVwqcMLFICIiwPS6/XC3c1sxRW4mWPeXyq+OW353sxbwg8NgOx9J/A3SucOcfJJ7y8u4b0m5dxjgXXwDYYwRTL+57t87S6Vbh1vdE54AhYsY5377f8xWcwsdUy/8lczbjGvG+Pk8R+8D4s3HXQgsfVOVwR9ONYSN1M8xqcfZdTU5SRKco05NEegVaJGtDkz32eGqrxv6llnVqNd1RfFjfLmFD8XozpPltaRsPNPPoyr9IPQsSip2bP97nhDZU5BzwUGqvnIQACOfRHm+ibZNC408YSs+d2zJxClSCHBCDx8YKfMD6j6m4/RS48Dl2T4t4hkMao7gnu8HM0skimFF6zaAeWNJ4PCv72ncQzJcd1tspJKGD+x/RUPP2MZ+333sO5rvV3gI+pgs2DH1afcxmlTHriMwn6DQHTsDhSAJAEvSuahbgK2IKyASFAZAGuRgy2OHvsmwwdkfM8ZvrHOoyBo5SseeMhrsRQMsLbaTLnw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: kube-system
    type: Opaque
