zigbee2mqtt:
  advanced:
    channel: 25
  timezone: Europe/Amsterdam
  mqtt:
    server: mqtt://srv02.lan.balti.casa:1883
    user: "!secret MQTT_USERNAME"
    password: "!secret MQTT_PASSWORD"
  serial:
    port: /dev/ttyACM0
    adapter: deconz
statefulset:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    feature.node.kubernetes.io/usb-conbee2.present: "true"
  secrets:
    name: zigbee2mqtt
  storage:
    enabled: true
    storageClassName: truenas-nfs
  volumeMounts:
    - name: ttyacm
      mountPath: /dev/ttyACM0
  volumes:
    - name: ttyacm
      hostPath:
        path: /dev/ttyACM0
        type: ""
extraResources:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      name: zigbee2mqtt
      namespace: zigbee2mqtt
    spec:
      encryptedData:
        secret.yaml: AgASZ3b20e7hQdZGa1X7Rf/Y+jbldDpcwxK2CtvHvUqLIVwolA/RdSF9AWfFHitmZODl/61o5gJPzG8MLX3X6zYoH6FTU6R+gYz5aYKTw2cbsyUL3Q2EFu5YOtsvOEkScoPBIpx4am/c8/od0U0kwvyFX3+zuLTe3wJo3MPJeLknW26hiA4RmtCUVc65r8BcDHa9tlDYYVGqmHhxjPcuEyYR6EOnUvGyZC5Sha90K3bNDgljLBEQGieFBi1cLxB7CQydEYVyndjY43PzVDyeyjw7qCqLntePiOCRzHhfquOdaWDd9/UO62W7JrjqJQBe3OGHNy8Y3A4FCLtlqr8sqQH9qg2Qod5pSEIFdgElnZukx6aBQUaIk4MRI1He7Gysd8GFrlD3rHsATpVxEy+d9Crev5BTy8IPKheIWvco8zyl68mLUS3N5TjI0O3F3yUBOncFKinomeGE6SdAZKl5yJ9bYMX4cAlcBSYKhOYsHPmeKO+EXhEotc0yAV64m6K/fth83aH1oXIUR+Isw+Up3hmun7U7Z5z3KYnmRtqgDmQJZlZdXRtbwZi/7v1HV5477tjFGoD+6sWO7R4+pBN5G+rLYFREcoTsGznub7vHRslpZhl6DQgL6MWF0S5Flv7QEQHoG/pHSVE7Z/hEwj5BDTS9gGr3xkc9Ndpk4SJus6Fo2SGegzLW2rYeYuiXAFCP2J2WIWw77lGW0YJ2UMOD3xN4wBJumFNWfRVk7jafaIQZAbNturLE0W68Ww32SbS4C+e+qPTVZMGOdUFDBeQFqqPki85RAvWuh2E47xgee8dCt5+rTByHXjqXjQxL0TL5NDygdqlUNRYqLkIiwyiGu09p+7cWMyvWPE4ojMrKFLhehwnWBNr2b3jFgNqc8pzrCvmEYlI8ItbUPw2v+CUe1ZkMPMQEdSF5+Ih7vqWIY0bqhSvmIMNINcLQpAFpG7qeKISfP3TAu9VBhwM3BuSqdf3f7b/7L6yBBpZsuKUCUwhstZ9f9mZUxXut23oE8PVsgxM63m4MOEKIzKJmthsq+83p0p9pg8K0l55zA6Bo
      template:
        metadata:
          name: zigbee2mqtt
          namespace: zigbee2mqtt
        type: Opaque
