strategy:
  type: Recreate

persistence:
  enabled: true
  storageClass: truenas-nfs
  size: 256Mi

service:
  type: ClusterIP
  ports:
    mqtt:
      port: 1883
    websocket:
      enabled: false

config: |
  persistence true
  persistence_location /mosquitto/data/
  log_dest stdout
  listener 1883
  allow_anonymous false
  password_file /mosquitto/config/passwordfile
  listener 9090
  protocol websockets

extraVolumeMounts:
  - name: auth
    mountPath: /mosquitto/config/passwordfile
    subPath: passwordfile
    readOnly: true

extraVolumes:
  - name: auth
    secret:
      secretName: mosquitto-auth
