strategy:
  type: Recreate

persistence:
  enabled: true
  storageClass: truenas-nfs
  size: 256Mi
  existingClaim: pvc-ef220cd3-127e-48d7-82ef-edc0de71c597

service:
  type: LoadBalancer
  loadBalancerIP: 172.16.40.51
  ports:
    mqtt:
      port: 1883
    websocket:
      enabled: false

config: |
  persistence true
  persistence_location /mosquitto/data/
  log_dest stdout
  listener 1883
  allow_anonymous false
  password_file /mosquitto/config/passwordfile
  listener 9090
  protocol websockets

extraVolumeMounts:
  - name: auth
    mountPath: /mosquitto/config/passwordfile
    subPath: passwordfile
    readOnly: true

extraVolumes:
  - name: auth
    secret:
      secretName: mosquitto-auth
