apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - nfd-api-crds.yaml
  - intel-igpu-rule.yaml
  - usb-conbee2-rule.yaml
helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: v0.18.3
    releaseName: node-feature-discovery
    namespace: kube-system
    valuesFile: values.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
