apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
data:
  DATABASE_URL: {{ .Values.databaseUrl | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.oidcClientSecret | b64enc | quote }}
  SESSION_SECRET: {{ .Values.sessionSecret | b64enc | quote }}
