---
repositories:
  - name: openbao
    url: https://openbao.github.io/openbao-helm

releases:
  - name: openbao
    namespace: security
    chart: openbao/openbao
    version: 0.25.3
    values:
      - values.yaml
  - name: openbao-config
    namespace: security
    chart: ./config
