apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pocket-id.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.data.accessMode }}
  storageClassName: {{ .Values.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.data.size }}
