---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: truenas-iscsi-democratic-csi-driver-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: AgBTfqNeqpZr8p3o9JD0hPv1Ts8kFs/kd+q8RxKq3uj8GiK2cag5TP3vevjIg+D+uVbpqrrkBvdueylnHIJqv6AhvjFYoWdzMv+z7+RS1giStO5RyiLEuYST6pJdlMeu6gg2YhrzzVVITuGtQVr3LoUPH8EJq/ZdiBodalCrZ96uOljf5aAfnq5jYq1X61FOoYimmDzMaS9DHb6ZGMVCXM7y7xXcH+OvHRt/HBrF2G3UuKNmQY/yYmCJSsbZxDy/Bh5MBeS+DZ40eTPVKcsfSnDGHZ9XkNmWH3muGJcFgFs7cZvDJU1GptcAI0ae6JtLrmRhqiMQgLcSxMqvkRFq9M7SDKgguSBa6bNsXij0OPb7qqZx3YUbM7h2rsjMWs8uFvuSAi5+x5SoxOU1RqFjI/owx7mQcxMMN8T8DuryVmOMRmIF6ZDAolRX26a/JO3Y8D+f3yU0Oi47SlBdz7ls6cuz8T+I1THaJpa/NUS6cOrOwd2UhObS7/PYeWhp6b+lTiYngr6Zkx+/49UU4SZ5JJWj3G4fLH3gq+slpzoB01jtR0xwMlH7LCDQe7dnulfwG+aKWIEaI5kOZHgsaylYrjFuQgGjdau9IFzYr1/ovFgr4wsuy7VGeyMARzb6MMj2DGKsW8Q6lRMIXqxfD5cB943c/DNSs0j+tngZNAn7hfX5s1QjO0VFU3xY+9kYpxjlH9CmQewHHQnILQdPwyOvUIr6L5RrMK93wyXsppoQxGd3qYCB30Ok+SMav7MWIu1cif5dLHwUtE8RbkhKEDlThwax8lFj8Urzl5Bj+wGnf80m9Rh7SXcP1fwFKoB/9tD35fAAssLFHKSWPu5IYpKQdCzUjPd+wCD3Tip+LJcJZXq0vZdyRqOO75lzah2pQu3qXa1rRukl3q+N3kfdFc2E5ME3gJheC6tilNdOOw6qgUxpsIYmq3pTZ2H7cYZJU3Pqm9wRnp7plvZE/F3J/Ts8I3pUwOV8I1YOMDWomD0GgI/QEfM1rO5V0Kv2x+VLpct4wt4Ie6iJk5IWYg+H2goLDcNsaQ69EhnkTKxC1w5xz2s++0gFw4j9MMifyvOn8xLMI2jEUrduksQ3SV+0JsWNIDjjEfpVzV6psY/1rUHYIGnQsL11UX3Z1w6KjiBlHg/M5ASrJQNPcmECw/QhbSmRS0izjMe2VfbEfCuq8iADd8r4nkNxA/YnI/Aa91q8Ny37qacU3ilftx7OKNqYQsYwjeGoAzNsv4QwDQ2aoTqWhP2a7aDPYiqxvSYOYp8wGu1xkn7hmKigEwLKGJ0mO+BKNb4OZaUITXkT2kh6pBxfzMAHWAvezTqAXSZf0A/hgB0BVF4LeyMeUlZc1upYGRKzJsXRmnynKopZUNygJXnuRS/1OPFqsPZyaFq3YZePhDDh6OCxMMbIWmaZlEI9k6/Ho4Q9gR+4v4XpuF4u6XINXUUgItGJ0t3zzSZVxNTNPCtKiDjSRrv2TTx0Fit46R3P9IR0AR+5H9thAzlyqhXYPWBWaxyKyUleNIAnop0JApVL/7ukcAVdsu53F+EymIVsEqtYFy5qZyFKczmFUFvyoN1H4t17bqvIRAnF7iq3XXr8GqKuBwtPk6HuIxoyra4/xPnrAuYLiEfmtNKywoq/P9GoajzzMzBmHGFIthhPqYbiCHeLxy3YCI+C/nmkOtktni1kuUA9WqgkDYEAeUsqRFDupgfoDt34SQ3bRsyO5Mq53H0pQIodWb4BYFUo3a4AyBd6+egScPnScwLa6mC4JxTaZVATOUiRrgKwsayjfnfLNxvJkqiPc0k=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
        argocd.argoproj.io/tracking-id: democratic-csi:/Secret:democratic-csi/truenas-iscsi-democratic-csi-driver-config
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: truenas-iscsi
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: democratic-csi
        argocd.argoproj.io/instance: democratic-csi
        helm.sh/chart: democratic-csi-0.15.0
      name: truenas-iscsi-democratic-csi-driver-config
      namespace: democratic-csi
    type: Opaque
