apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "172.16.40.48/28" # Use "blocks" instead of "cidrs" Usable IPs: 172.16.40.49 to 172.16.40.62
  allowFirstLastIPs: "No" # Required in Cilium 1.16+ if reserving first/last IPs
