apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  volumeName: pvc-c57d8c1c-55c0-4ef0-81a4-43ba192bf5ef
  resources:
    requests:
      storage: 1Gi
