replicaCount: 1

image:
  repository: saicismartapi/saic-python-mqtt-gateway
  pullPolicy: IfNotPresent
  tag: "0.10.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
podLabels: {}

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    memory: 256Mi

env:
  - name: MQTT_URI
    value: tcp://mosquitto.home-automation.svc.cluster.local:1883

envFrom: []
  # Populated by deployment template to reference the ExternalSecret

# Probes - disabled as container has no HTTP endpoint and minimal tooling
livenessProbe: {}
readinessProbe: {}
