apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http-route.yaml

helmCharts:
  - name: syncthing
    repo: https://k8s-home-lab.github.io/helm-charts/
    version: 4.0.0
    releaseName: "syncthing"
    valuesFile: values.yaml
