apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com/quidome/gitops-lab.git
        revision: main
        directories:
          - path: applications/*/*
  template:
    metadata:
      name: "{{ .path.basename }}"
      labels:
        type: applications
    spec:
      project: default
      source:
        plugin:
          name: helmfile
        repoURL: git@github.com/quidome/gitops-lab.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        # Extract namespace from path structure demo/<namespace>/<app>
        # Example: "demo/frontend/nginx" -> ["demo", "frontend", "nginx"] -> get element at index 1 -> "frontend"
        namespace: '{{ index (splitList "/" .path.path) (sub (len (splitList "/" .path.path)) 2) }}'
      syncPolicy:
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
