---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBUpXAjo2spIi2QFRU1idcdBVC9+0t8EL+hB59zvn3ntbUdkIk/0L79nIgaPXEpW5L89iy86xi7NtGzE98oEf5QOGvDH5dKJBTfY0PQ9elonaV5QB/R0Wo4lZZN1Ll4y+Gu18gfOdXtTzJ+y0bOn5DahfYrI43s+czqo/iGPBrgSyL5qp8tR9q1m126IwhJMYVW5H5xAP+/hx64qEbaN4zh0bO9Gen35iAvWva8IsShPa1BXOSb1BtYW7gX+QSDTxjaLhJWHrUUji1SgV+UBONRPXubU7NjVK1awL5Y5679W/IwbdP0TWKza3EX/xLwQbLIgEyJwBLsUaLAxkRzpzNZ8ChPH754AKBDh0j2LDniuwts6CJKcxo25zrDc51fzRNg4rlDsdo2ncap8geKdv4al66JtQmf4vF2RnhuGD/9OEHlofbvw+ILrxBiQ36EV0YKyWvVGNx0+yhfc2iA7Mvhaq9sLSTCiVDVAzmXv5EJStAKFmHlOVGgm8Q0lwzgC/D/U47LBT5PtzG2UHEdhLedjwQLFDxta8ut3ffMiz3Gsb5UR2z0HRBGYtml8DoJrt7ynVWHtd4tbMIXGZAjwr/55oE0ib7wGqI8/LucQifURbqJu4BQQPRw6Fn+HF/x5qc+ie8j5XfPRttK6oSnRvkjbnTDF5irhQyBCYybZk/9MIyU0czGSubAcoPduPPumdvDxUtJ6JLUZJG6QRXwLmtgqnox/lZVlHDjZ8n3sBJ0IZkyzNF18qHk
    email: AgBVSoPhJoOEfORdhbGmGDQlvOeTyiIQPCR0M9dJL+CAvaiVAxzvE3sdtISO/HY18+Jcaf5Bi9JuX0DXTiquw78FZZ4V5uB1rWB2HiJsHy0gFvbmnoL85qYSYgsapDLVEwaPsji2oHkoUV0wGEFsYCjtW9C1MZg0BEj32KXuCu2vwNmNULqCGub+ldSp8LNNbvVV1BKEHXzvLu/DYnc84+fxlGlKSXNblJFOBC2MBxjATcovmYgaz38e56TEwzH6mq1nmquAbkHDN0hl34kw85Qxn4SinfeFIE25IFAtjCnNoufOOepkknQu2X3QvhjNiUorcc7p6qZ9Y3YAzuFK9L74VeObnpc2Yjxbv55BMIWVKR3xsdazJTDoNk80RJwphAUWTinoRqZ4NV/eEG+tUuIscXr0o3s2CHxlZxK7flaK+s+6X9PURRVq8gVlNPfHU7AwjhSRcd/myndKb3LbB/ACqV/g68XmTdU2pNvz9EkIug+f7znEps4vPLPKnwM1muleAYGPMZLl4niLMnj4Ukg5p5wBbLaLn298rYYq5N8GU1PTJEbrVmKsJtcRwj85ojSTPDn1F+3S9N9KtjjigUVtndYvzJVPcn9H7JtHrW9zCTJzxvURBsjCLcJlvdKi95uhuqvRGK466DKlrv+Bfi6TczqXc1eUWRdpaNNUcuMvYnCh78KQ4qUONComz3wXdoxjg0PU0nbebfkrvc8ovLWXzg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
