---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCrf0a6uX4y/XR7IKnlj2o4ZMF26gukUGSqd2CbKWpD7M08sjsp4i50ksE+mkrPVNKjzLKNmBoxIYprzkk+2rR9TMgsowtoNF8QyQh/DBbslCjJiQl9V4zGkPC7d61J+kxx374DLLcwz0mAu2n59iySOdbbjFFc8rxLcI5NMAEy6J6HCaOaoaCUgMoyGvBnTezId2Fn8po1Ilb75dP8Hxxrtxvl8aq1+KFnqz/Q2tX3RY5WRGml+7hp0C3TwyfgCCIoscwpR7fbrDe9+6AVq/FFTMR9I3q9LTxEVwK4Be3JUbmQCAih/4HDvlCsHHpjTI8qycdLe7h0THrgiri7vV6NDVPYaASY6+dWP7Mt+KMbehEunbE035zrVGY9evOlf8luYahb3jrEd9v+vjA2xU93vK7OywvglG1HTHL4RVs5b+Dc6F1ZK7Bykk8jyV1JWj00c45IoILek96Visr4P6mCtswzFW6Ih5l+SIKcf5+1mHAOmau2o4zmko4Pp35GTghFmlPSV7CTt0Fba8MNjZ7vzX6/LGH/smH4h4Qe2ttOzDuhQ1/9PSrmIaD4CGdgVw1URhfz55oM5MnjF3UYLGasHo/tb0II44jFtrluOFmATfgrcYAFQA4YUzUtfAQEm4SBea8DYrzAIXCiW0M6GYbTBbAVjiE0LXQiVcBSnaK527xBwrIFvGZt+qY5XMBlggftHgrS8GvtBjULLvIt0vqdGKBst4poBoPiGAdL+0PkEt2eH3mOvKRF
    email: AgCP7IcnltBT5M4Udz6O9AefxF/bvbVglinhTPRcXcDy6vtgehuQz5JSaplLjETD9ga6M0lQBo0zVzqHxOBUa8JpRDdXdrqbUvkRxoqmz2Aawem96ETJ0KugqHFruNaLrv7B/hJwlYx67j1lMmcRdD1aHgCALULRKoPujCWQ87j6sHi/Q0K7hStIPleSqCownTnhRQJUH6hmLqCdMMnXTCS1OBthSas/YUBZEdXQe3HbZ0BGD1dKAcelwSF9PO36ODpzzG5E70e9NLIIkN41B6ajidAk6lRThQKMaHlgZdIUSCDYjdV9jpZ/JXbS7QsPulmRPp53/NiBgTHzTR4oubLme2eP0X1+pbcWZWPu1LNwAVEUjD7kD9AX2k7GFmHEml3+jp1QANgcZtpWERnw6RdNnz2xK2iOOCrxg84oixmclZ0KEBuvixUdl+fwQZ7UmoaSTOzEF77q6+hm4PPGWPoSvmOOanmxHxUOHz6oNEbCebomiC7JufQdOFzuOObPm0xXHuvqLErAubtntOW9xI9QfDW5hcLvPMv4OcNe8EU0q7bH4AS3GUTSv4o7TS1l0S6WJtqUb5JfodbcU4e+r7Hkxxl0PLzYtPUJDTgkT5BEKlYWKtaVwGUoQqgul6owSsNTmnXDOhWxWXC1G34sM7PzwesULOBKu+JM1vbeUNGlfMGeNDOW0evdRhOuqBu+dg9qlanf1jx4MW5AJj8X6AVfgg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
