apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: gitops
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind | quote }}
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath | quote }}
        property: RENOVATE_TOKEN
    - secretKey: RENOVATE_GITHUB_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath | quote }}
        property: RENOVATE_GITHUB_TOKEN
