apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-quidome
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: Validate=true
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  dnsNames:
    - "*.quido.me"
    - quido.me
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-quidome
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  revisionHistoryLimit: 1
  usages:
    - digital signature
    - key encipherment
