apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.scfg: |
    base-url {{ .Values.config.ntfyBaseUrl }}
    http-address {{ .Values.config.listenAddr }}

    alertmanager {
      silence-duration 24h
      user ""
      password ""
    }

    ntfy {
      topic {{ .Values.config.defaultTopic }}
      priority-low-labels { severity = informational }
      priority-high-labels { severity = warning }
      priority-urgent-labels { severity = critical }
      icon-low https://raw.githubusercontent.com/prometheus/prometheus/main/web/ui/static/img/prometheus_logo.svg
      icon-high https://raw.githubusercontent.com/prometheus/prometheus/main/web/ui/static/img/prometheus_logo.svg
      icon-urgent https://raw.githubusercontent.com/prometheus/prometheus/main/web/ui/static/img/prometheus_logo.svg
    }
