apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.scfg: |
    http-address {{ .Values.config.listenAddr }}
    alert-mode single

    labels {
      order "severity"

      severity "critical" {
        priority 5
        tags "rotating_light"
      }

      severity "warning" {
        priority 4
        tags "warning"
      }

      severity "info" {
        priority 2
      }
    }

    resolved {
      tags "white_check_mark,resolved"
      priority 2
    }

    ntfy {
      topic {{ .Values.config.ntfyBaseUrl }}/{{ .Values.config.defaultTopic }}
    }

    alertmanager {
      silence-duration 24h
    }
