repositories:
  - name: bjw-s
    url: https://bjw-s-labs.github.io/helm-charts

releases:
  - name: saic-mqtt-gateway
    namespace: home-automation
    chart: bjw-s/app-template
    version: "3.7.3"
    values:
      - values.yaml
  - name: saic-mqtt-gateway-resources
    chart: ./resources
