zigbee2mqtt:
  advanced:
    channel: 25
    network_key: "!secret network_key"
  timezone: Europe/Amsterdam
  mqtt:
    server: mqtt://srv02.lan.balti.casa:1883
    user: "!secret username"
    password: "!secret password"
  serial:
    port: /dev/ttyACM0
    adapter: deconz
service:
  type: ClusterIP
statefulset:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
    feature.node.kubernetes.io/usb-conbee2.present: "true"
  secrets:
    name: zigbee2mqtt
  storage:
    enabled: true
    storageClassName: truenas-nfs
  volumeMounts:
    - name: ttyacm
      mountPath: /dev/ttyACM0
  volumes:
    - name: ttyacm
      hostPath:
        path: /dev/ttyACM0
        type: ""
extraResources:
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: zigbee2mqtt
      namespace: zigbee2mqtt
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: openbao
        kind: ClusterSecretStore
      target:
        name: zigbee2mqtt
      data:
        - secretKey: secret.yaml
          remoteRef:
            key: zigbee2mqtt
            property: secret.yaml
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: zigbee2mqtt
    spec:
      parentRefs:
        - name: gateway-internal
          namespace: gateway
          group: gateway.networking.k8s.io
          kind: Gateway
      hostnames:
        - zigbee2mqtt.quido.me
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: zigbee2mqtt
              port: 8080
              weight: 1
              group: ""
              kind: Service
