{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "proxmox-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxmox-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "proxmox-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /pve
    params:
      target:
      - {{ .Values.proxmox.host }}
    relabelings:
    - sourceLabels: [__address__]
      targetLabel: instance
      replacement: {{ .Values.proxmox.host | quote }}
{{- end }}
