driver:
  existingConfigSecret: "truenas-nfs-driver-config"
  config:
    driver: freenas-api-nfs
    httpConnection:
      protocol: https
      apiKey: TRUENAS_API_KEY
      host: TRUENAS_ADDRESS
      port: 443
      allowInsecure: true
    zfs:
      datasetParentName: datapool/k8s/nfs
      detachedSnapshotsDatasetParentName: datapool/k8s/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: TRUENAS_ADDRESS
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: root
      shareMapallUser: ""
      shareMapallGroup: ""

csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
  - name: truenas-nfs
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4
