apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: "http://openbao.security.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: openbao-approle
            key: role-id
            namespace: security
          secretRef:
            name: openbao-approle
            key: secret-id
            namespace: security
