{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vikunja-postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vikunja-postgresql.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  podSelector:
    matchLabels:
      {{- include "vikunja-postgresql.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: vikunja
              app.kubernetes.io/instance: vikunja
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
