---
DNS1: 172.16.40.1
DNS2:
persistentVolumeClaim:
  enabled: true
  storageClass: truenas-nfs
serviceDns:
  loadBalancerIP: 172.16.40.53
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  annotations:
    "lbipam.cilium.io/sharing-key": "pihole-dns"
replicaCount: 1

dnsmasq:
  customDnsEntries:
    - address=/lan.quido.me/172.16.40.78
    - address=/web.quido.me/172.16.40.68
    - address=/grafana.quido.me/172.16.40.68
    - address=/overseerr.quido.me/172.16.40.68
    - address=/plex.quido.me/172.16.40.68
    - address=/proxy.quido.me/172.16.40.68
