image:
  repository: renovate/renovate
  tag: "43.264"
  pullPolicy: IfNotPresent

cronjob:
  schedule: "17 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 600
  suspend: false

renovateToken: ""
githubComToken: ""

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    memory: 1Gi

securityContext:
  pod:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

renovate:
  config:
    platform: forgejo
    endpoint: https://codeberg.org/api/v1
    onboarding: true
    requireConfig: optional
    dependencyDashboard: true
    repositories:
      - quidome/gitops-lab
      - quidome/gitops-apps
    extends:
      - config:recommended
    labels:
      - dependencies
    timezone: Europe/Berlin

extraEnv:
  - name: NODE_OPTIONS
    value: --max-old-space-size=768
