---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-pihole
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCOHDSjpEyyBIODNfNGseptAixUnECYenc7cgqfvCx0dXMiWdBYOkS+xCSZKMXMOIFyHAY9hdMqRcmqtPSm7jopOvi5PDonZJAitdyJujP3SwX48lGi2Qig3O/JguFPeytDCm6YL89oxfwlNYLvjU9F9LVsCpkqUSdg/ZTvXTgQKPhGsJJBnyKRomRMPayd0aV3aiMVAe4Q4biFF4ngzgnwPoIdv2zfPyXmmy/xn3N3NRWLZa3sdMo3BzVIXR3kVOUpU+mj6UXjvwoiNAo5lMt5Z+vQzEC920hLA7n7pp7u8m9/HaBAyhS8ixDuaRniJwO38xbscAjY0R5eDIig8pLH8ZoFo4Ti3xSy05C0svm2gORu79Cpzue8E8mZ4k6rnkRraBQlBL8v5fbeu9fWqfyHaBHxk/kow6XVxWeZvFloh8dQBN6yX9fPLwBXcOtKyHZ+Dtu6EcziXijGMcsQDH52OLPLeKPNXzkT1nU5cFlDtFrNtzh6Xi7/fd8V52sTw2Rz0N3XRGvk+GKW4SqKAzDpUOzNjiL6iL5NxQC8WXC4pyczlUgk4mXv7nO0KBEbk/Cy+lWq7pxHs7Gl8xldA1lLGNQrztw86eA2Ppd+waI5Ri6gSwXqsR8WOigkx7SLRao5mSgLFGU9QFdPzXbsOokPHkPcSRo5Z30zzn0seuZ8nJXel55J/ms08PA+X2AaqAUWeMe7GE9tkqdjqExoulHhwuDK/Q==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-pihole
      namespace: external-dns
    type: Opaque
