---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns-pihole
  namespace: networking
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgAocGkv1RRi6nzu0wP3W/+YIRfx3rSBPi0tNtmn+1OnzJDFV/zoLWdbClaqpFzyQhaslyezX03i41X89TWz7OieTFH1jYvAgSvm0AGWaMHAs4uSPYlJfCDRJecHSHarWTLrNKpm+6MV/I1k4Fqc2p//xs+XOI2x52vSHKHvmnFZYWnpqP1QitI6TJx6vlFulPuZ+teuyIkawtpLHc5a7F6ghttMJfkPbuijjUbdhrghIdvkDh1xHMxtJRhDuaP3b7QDnW1oOjhSe2Q3480ztS6QogycAbwaF7tGXBFdd+lTxWX0YkX8uCV5i9OsQIN448WSwzyu/55nXMWU8mGpI4dWzipnogeghGgqPUlFdOoiOAcrF8A5D6wi1XMGs9uuhZLRlG5+z0xPx5sMGgqfrs+8S0zS+/4L5r1X3kgCyArdSj1IaIMUR/59GCo/z0B/310Q7k74Arn4JZLbaBSgxp2M9ZIJk/dtiqbcumEl9rrRMMNw7PQQmMAh1v3tMVfeuO1fF9u2KVBAAfRX07nIZQOjOiymCoIwYgTo0USimacaQrllpKXDDVpRGOyE5iYvFL5xi/mrk5BCrJKavI58k5/9Ov0olB2Gj8tJGIc8LQI9pNpG3xWSE3Ag1Ix/sM3FpBQsFHOnDOrFwbU1LveReuQlKZvCiJTWJGoxBd1Ihq7DysqeDPV54LvqXUz0W+2y3CIDWDrSHbg2Fh2yrjJG1gdKeK5W7w==
  template:
    metadata:
      name: external-dns-pihole
      namespace: networking
    type: Opaque
