apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-pihole
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: external-dns-pihole
  data:
    - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
      remoteRef:
        key: external-dns
        property: pihole-password
