repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

---
releases:
  - name: demo-nginx
    namespace: demo
    chart: bitnami/nginx
    version: "22.4.4"
    values:
      - service:
          type: ClusterIP
          port: 80
