apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml

helmCharts:
  - name: external-dns-pihole
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.17.0
    releaseName: external-dns
    namespace: pihole
    valuesFile: values.yaml
