provider: pihole
extraArgs:
  - --pihole-server=http://172.16.40.1
  - --pihole-api-version=6
policy: sync
sources: ["gateway-httproute"]
triggerLoopOnEvent: true
domainFilters: ["quido.me"]

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 64Mi
