provider: pihole
env:
  - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: external-dns-pihole
        key: *name
# podAnnotations:
#   secret.reloader.stakater.com/reload: *secret
logLevel: debug
extraArgs:
  - --pihole-server=http://pihole-web.pihole.svc.cluster.local
  - --gateway-name=gateway-internal
  - --pihole-api-version=6
policy: sync
sources: ["gateway-httproute"]
triggerLoopOnEvent: true
domainFilters: ["quido.me"]
# serviceMonitor:
#   enabled: true

