provider: pihole
env:
  - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: external-dns-pihole
        key: *name
extraArgs:
  - --pihole-server=http://172.16.40.1
  - --gateway-name=gateway-internal
  - --pihole-api-version=6
  - --policy=sync
sources: ["gateway-httproute"]
triggerLoopOnEvent: true
domainFilters: ["quido.me"]
