apiVersion: v1
kind: Secret
metadata:
  name: freshrss-auth
type: Opaque
stringData:
  FRESHRSS_USER: {{ .Values.freshrssAdminUser | quote }}
  FRESHRSS_PASSWORD: {{ .Values.freshrssAdminPassword | quote }}
