---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret_unenc.yaml: AgAezzgKn+r24ziyDTN/ONas7OBKvYMS78xDH7w04kT2C2dz1jHg//D/42tBEdF5ZFSNFL2wXFrFHzDnjoSt4fqQIkIqPo7tfXre34diRiyaKPnzr+GIPdQ7J9STacCTVPBs7bPC3H07fvKulKrtRa4boX4qqrfOIrf2G72+zMcprdqVlVHO8gjnioiTqCnGaXiekvXXFv8Yy0wLnhZ5nH18IY5uxraYABxiu+FE4TfhjUbrOxid1WwYqoAKy5NtTmZSnawE1kXoZBOucLjZwdnFDN7O/eQu1B8MABD8JCSW9xB5xMqDJ940bG7BrXrZBwhm0yT8gOT1+FB/Wc1CRUmSnSU7h4fqBeZHBvyPSwzws7bTGoVO/3vCtRxVpFXCqeMdzwt4VHhEBGtqTBUdWNIlK12aNgqmcM5BeSna5bvtm3q3bWazXvdTDxXRtWjXS1OjKjTRaPwsFn63ufUpRcgDfoj+vaF3n34Vqv75QNwkKc1F122Rhu1J72wKcWA4//Yk9snmR6GIpRdK2tMbT/9G+GvMMUrQDh359/z/8KHTAlXC1ZAsqhpEMeAiN4QwOPQjsFNzSmhjLkxjcdfLECIPPRYMc3zSL8CtOfi+06PebaSHpqWi0vq1vvS+2yX4SldbBwfx2u7iBrFuiSm+ayOjStXkCqXzaHk1aY4oLUa3CxyuMLyy5BzsPyTwh7Cl4bHFRaw3rusbxBezwOQlWrTw0c+cFothE3zUXECvRWivg1iH83pmtL+uGUwucRMcOBr2ypFkgt5QCm4d8a2Dvmlf7vwYV7tMQcznIXove5x/gvzw0nYb7USOq6EzAtS1aY8xm0dEHOCe9HwNhMxKAz4Q8ckxkzvMfwV0cNVQQ5rH5rzrlt7WPKhEjd04YBht9fYQV+v19GAJgheHm7Ha3/+1XYthXnX1b3mdIgEJYLOdAe02s8Hkz2tJT0SWZDMnXAYxZjpaRhV9IoyXIiKNpIiNRyQ/l7XDdjhihQWjsD458qj6c4Qm0asRHi3q7mInILYa5jRpyD+qgWOZ7pQujbFwU8s5jdlpVJbebTym
  template:
    metadata:
      name: secrets
      namespace: zigbee2mqtt
    type: Opaque
