---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tmp-secret
  namespace: zigbee2mqtt
spec:
  encryptedData:
    secret_unenc.yaml: AgAtbKSQkElfccdwpDpsYKXuJGbx0yFToDVcdO8ttdZNJnZBwYG72qRjnMBuko3nyah0RvLisT4NRSzyPFvijacugJ+dsbrBpN9iWkmAxoZp8tJvnulNNIvEV8a18HYxjzTcIhWHP8Y4Fym8A3Cb1zGhX5lnj/wgFEeYu5SY5FjtA+tydhN4YetK3tQeWYWOMM+wuZr5Rp/zoBPCrxRIEAK+Nepx4vO8ujUv9DYt/jQRILM+Zmm8/XoJy1m9b8nZNAhZrloG/slVwmtyAW7LE6tSZYLyCDE0/wmSBIOb3gk1IWbzg6mtH0YLDQUeafNUq3ki1kbHyNrnxa8nCW5UZzLNTtbq9Yp2mXGkc1eXassQBKMlA91pHU3I6puOGYR60cevr3qC7hOsSnmpSv91i+836dZJ6REP1zEgkXUcMB7UDQ626kcFrX2TMARO58OFQdX3XM1ony2/gV1JPpNiRqPTZmYYrBabYuSm/MuknewsXIjTPdULICp/v/fmcvYIHJnhVekRQopHI9u1Q8jgIB1Numj0dK5zRgC+blRYshapo98LPIKSHr/c6cmN1JY4zDqjteAyUuciNEFqta79Z+59ks61LUvfVDM36qUUjIB1O7bgCsg9uqoHUexGHIPN0vOviCpnqMAai7vyBwcQnHFTgvCL/NZvmho5Qhoc+jSPzg1YK1cZVdml+vMRUNTvXgsuzQcYKXbuJaEujKneasll9SHokLp57ZqFqxhZWkWiILyXERN8xu8zfiMJM3yismvVqINaDJ6VCkSoZEXFzPN2OTlKUSQC53+TH6qehobD0JwTOhknFo7pKIHiGnWs+EiA3N1FlwKkVBwpurFbqi0CKhBTD45Yjd2jlg9ha7XkZ5veyLu9B/YRNG2gn3fmCXBwRpCLtdu6g069d4TEAV7EBS/47hqo7YUoNcwU0eltDZVCarUET8nSDgus5Oh2BLXTim5LulJi7rVuCVJ56aNOJk5rvOGbrQ9qyVJVEtDznVgIQOzAoCtshO+/1C8+7NyijbvyxQptOgdBtgUb0eS1OGrWSoBANP4ipktg4wxqZW7tpBs1UJ714K+1mw==
  template:
    metadata:
      name: tmp-secret
      namespace: zigbee2mqtt
    type: Opaque
