zigbee2mqtt:
  advanced:
    channel: 25
  timezone: Europe/Amsterdam
  mqtt:
    server: mqtt://srv02.lan.balti.casa:1883
statefulset:
  storage:
    storageClassName: truenas-nfs
  volumes:
    - name: usb-device
      hostPath:
        path: /dev/ttyACM0
        type: CharDevice
  volumeMounts:
    - name: usb-device
      mountPath: /dev/ttyACM0
