zigbee2mqtt:
  advanced:
    channel: 25
  timezone: Europe/Amsterdam
  mqtt:
    server: mqtt://srv02.lan.balti.casa:1883
    user: "!secrets.yaml MQTT_USERNAME"
    password: "!secrets.yaml MQTT_PASSWORD"
statefulset:
  nodeSelector:
    feature.node.kubernetes.io/usb-conbee2.present: "true"
  # secrets:
  #   name: secrets.yaml
  # storage:
  #   enabled: true
  #   storageClassName: truenas-nfs
  volumeMounts:
    - name: usb-device
      mountPath: /dev/ttyACM0
  volumes:
    - name: usb-device
      hostPath:
        path: /dev/ttyACM0
        type: CharDevice
