apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntfy.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ntfy.labels" . | nindent 4 }}
data:
  server.yml: |
    base-url: {{ .Values.server.baseUrl | quote }}
    listen-http: ":{{ .Values.service.targetPort }}"
    cache-file: {{ .Values.server.cacheFile | quote }}
    auth-file: {{ .Values.server.authFile | quote }}
    auth-default-access: {{ .Values.server.authDefaultAccess | quote }}
    behind-proxy: true
