apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mosquitto-auth
  data:
    - secretKey: passwordfile
      remoteRef:
        key: home-automation/mosquitto
        property: passwordfile
