apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mosquitto-auth
    template:
      engineVersion: v2
      data:
        passwordfile: |
          {{- range $user, $hash := . }}
          {{ $user }}:{{ $hash }}
          {{- end }}
  dataFrom:
    - find:
        path: home-automation/mosquitto/users
        name:
          regexp: ".*"
