apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: usb-p1-meter
spec:
  rules:
    - name: usb.p1-meter
      labels:
        feature.node.kubernetes.io/usb-p1-meter.present: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor:
              op: In
              value: ["0403"]
            device:
              op: In
              value: ["6001"]
