apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-graphics
  labels:
    type: infra
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  rules:
    - name: "graphics.intel"
      labels:
        feature.node.kubernetes.io/graphics-intel: "true"
      matchFeatures:
        - feature: pci.device
          matchType: exact
          value: "0300:8086"
