apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery
    version: v0.18.3
    releaseName: node-feature-discovery
    namespace: node-feature-discovery
    valuesFile: values.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
