apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://codeberg.org/quidome/gitops-lab.git
    targetRevision: main
    path: infrastructure/gitops/renovate
    plugin:
      name: helmfile
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
