# driver.config is injected via vals in helmfile.yaml.gotmpl

csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
  - name: truenas-nfs
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4
