# driver.config is injected via vals in helmfile.yaml.gotmpl

csiDriver:
  name: "org.democratic-csi.iscsi"

controller:
  driver:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi

storageClasses:
  - name: truenas-iscsi
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

node:
  hostPID: true
  driver:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /run/current-system/sw/bin/iscsiadm
    iscsiDirHostPath: /run/current-system/sw/bin/iscsiadm
    iscsiDirHostPathType: ""
