# driver.config is injected via vals in helmfile.yaml.gotmpl

csiDriver:
  name: "org.democratic-csi.nfs"

controller:
  driver:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi

node:
  driver:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 50Mi

storageClasses:
  - name: truenas-nfs
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - nfsvers=4.1
      - rsize=131072
      - wsize=131072
      - hard
      - noatime
      - nconnect=4
