---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas-iscsi-driver-config
  namespace: democratic-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: truenas-iscsi-driver-config
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        key: democratic-csi-iscsi
        property: driver-config-file.yaml
