fullnameOverride: metrics-server

args:
  - --kubelet-insecure-tls

livenessProbe:
  timeoutSeconds: 5

readinessProbe:
  timeoutSeconds: 5

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 128Mi
