apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  suspend: {{ .Values.cronjob.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Release.Name }}
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        spec:
          restartPolicy: Never
          securityContext:
{{ toYaml .Values.securityContext.pod | nindent 12 }}
          containers:
            - name: renovate
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: /opt/renovate/config.json
                - name: RENOVATE_TOKEN
                  value: {{ .Values.renovateToken | quote }}
                - name: GITHUB_COM_TOKEN
                  value: {{ .Values.githubComToken | quote }}
{{- with .Values.extraEnv }}
{{ toYaml . | nindent 16 }}
{{- end }}
              securityContext:
{{ toYaml .Values.securityContext.container | nindent 16 }}
              resources:
{{ toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate
                  readOnly: true
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: config
              configMap:
                name: {{ .Release.Name }}-config
            - name: tmp
              emptyDir: {}
