apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "saic-mqtt-gateway.fullname" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: {{ include "saic-mqtt-gateway.fullname" . }}
  dataFrom:
    - extract:
        key: home-automation/saic-mqtt-gateway
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
