{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "saic-mqtt-gateway.serviceAccountName" . }}
  labels:
    {{- include "saic-mqtt-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
