apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: gitops
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: kv/gitops/renovate
        property: RENOVATE_TOKEN
    - secretKey: RENOVATE_GITHUB_TOKEN
      remoteRef:
        key: kv/gitops/renovate
        property: RENOVATE_GITHUB_TOKEN
