image:
  repository: xenrox/ntfy-alertmanager
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 32Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

config:
  # ntfy base URL
  ntfyBaseUrl: "http://ntfy.observability.svc.cluster.local"
  # Default topic for alerts
  defaultTopic: "alerts"
  # Listen address
  listenAddr: ":8080"
