master:
  namespace: nfd

worker:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  sources:
    - usb
  config:
    customRules:
      - name: conbee-ii-zigbee
        matchFeatures:
          - feature: usb.idVendor
            value: "1cf1"
          - feature: usb.idProduct
            value: "0030"
        labels:
          hardware.type: "zigbee-controller"
          zigbee.controller: "conbee-ii"
