---
repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io

releases:
  - name: external-secrets
    namespace: security
    chart: external-secrets/external-secrets
    version: 0.12.1
    values:
      - values.yaml
