apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  provider:
    vault:
      server: "http://{{ .Values.service.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.service.port }}"
      path: "{{ .Values.kv.path }}"
      version: "{{ .Values.kv.version }}"
      auth:
        appRole:
          path: "{{ .Values.appRole.path }}"
          roleRef:
            name: {{ .Values.appRole.secretName }}
            key: role-id
            namespace: {{ .Values.namespace }}
          secretRef:
            name: {{ .Values.appRole.secretName }}
            key: secret-id
            namespace: {{ .Values.namespace }}
