{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      namespace: {{ .Values.httpRoute.gateway.namespace }}
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.port }}
          weight: 1
          group: ""
          kind: Service
{{- end }}
