repositories:
  - name: k8s-home-lab
    url: https://k8s-home-lab.github.io/helm-charts/

releases:
  - name: syncthing
    namespace: file-sharing
    chart: k8s-home-lab/syncthing
    version: 5.1.0
    values:
      - values.yaml
  - name: syncthing-resources
    chart: ./resources
