strategy:
  type: Recreate

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    memory: 256Mi

persistence:
  data:
    enabled: true
    mountPath: /var/syncthing
    accessMode: ReadWriteOnce
    size: 20Gi
    storageClass: truenas-nfs
