apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "team-postgresql.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
