apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-codeberg
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  type: git
  url: {{ .Values.codebergRepoCreds.url | quote }}
  username: {{ .Values.codebergRepoCreds.username | quote }}
  password: {{ .Values.codebergRepoCreds.password | quote }}
