apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-github
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  type: git
  url: {{ .Values.githubRepoCreds.url | quote }}
  username: {{ .Values.githubRepoCreds.username | quote }}
  password: {{ .Values.githubRepoCreds.password | quote }}
